name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers on tags starting with 'v', e.g., v1.0.1

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Concurrency Tests
        shell: pwsh
        run: |
          # Start the server in the background
          $server = Start-Process -FilePath "build/win64-echod.exe" -PassThru
          try {
              python test_concurrency.py
          } finally {
              # Ensure the server is stopped even if tests fail
              Stop-Process -Id $server.Id -Force
          }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/echod.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}